### ISSUE TITLE
Add 'show me all the unlabelled images' button

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/curate#116]
> Does it make sense to also show a 'show me all the unlabelled images' button? I.e. quickly identify images still needing labels?

Yeah quite possibly. Right now it doesn't require an exact match - if an image has all the selected labels and then some more, it'll still show. So we could require an exact match and then deselecting all labels would show only unlabelled images, but then we'd need another button to show everything. We could possibly use the accordion itself as a toggle for that - require exact matches when it's open, show everything when it's closed?

_Originally posted by @philipjackson in https://github.com/gliff-ai/curate/issues/115#issuecomment-867580063_

**Comment by joshuajames-smith** [comment]
I've designed an icon for displaying all unlabelled images - located in the google drive as per normal, under tech team > UI/UX > manage > Display Unlabelled Images. May require some further thinking around UX as due to issues in following sprints.

_Icon_

![Icons  08-09-2021 -119](https://user-images.githubusercontent.com/83074763/133791514-9a2bcbd3-6ec7-405d-a05f-6426a8ebb603.png)

_Mock-up of expected placement on current staging._

<img width="1239" alt="Screenshot 2021-09-17 at 14 35 54" src="https://user-images.githubusercontent.com/83074763/133791496-a6e9424b-c49e-4262-af23-fc23e41c8c80.png">

**Comment by joshuajames-smith** [comment]
https://github.com/gliff-ai/roadmap/issues/51 - link to same issue in 'roadmap' instead of 'sprints'
