### ISSUE TITLE
UX design for whole-image labelling

### ISSUE THREAD

**Issue by SilviaZeta** [gliff-ai/curate#89]
**Is your feature request related to a problem? Please describe.**
We need a design for whole-image labelling in CURATE. We should be able to add and delete labels to each thumbnail image. See also #49.  

**Describe the solution you'd like**
?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joshuajames-smith** [comment]
I've changed the current icon we are using in the staging platform to that of our 'label' icon to give more context to the function. I have gone white but this obviously might not stand out on certain images? 
I kept the green to allow for a tool-tip hover state to help the users understand the function. Is there a possibility to have this icon's colour determined by the surrounding coloured pixels?

![Curate Layout -  medium images  – w- image labels](https://user-images.githubusercontent.com/83074763/121718304-13467d00-cada-11eb-86f0-eaa8fcf1a44e.png)
![Curate Layout -  medium images  – w- image labels  hover state](https://user-images.githubusercontent.com/83074763/121718439-3a9d4a00-cada-11eb-9591-bf74d3b6fec9.png)

I've designed two options in order to label the whole image. 1. pop-up; 2. sidebar. With two different ways to show the user which image they are engaging with. The sidebar is most like the UX experience across curate: minus the pop-up created from creating a new collection/project. Should this too be in the sidebar rather than a pop-up? [#38].

The labels are added more aligned to the search filters in that the UI component is enclosed with a cross to close and multiple can be added and dynamically grows the list, while the specific annotation labels (found in annotate) are more about having a constant list to access to turn on and off.

![Curate Layout -  medium images  – w- image labels  version pop-up v1](https://user-images.githubusercontent.com/83074763/121718667-73d5ba00-cada-11eb-9537-e4092dbf27d3.png)
![Curate Layout -  medium images  – w- image labels  version side-bar v1](https://user-images.githubusercontent.com/83074763/121718675-77694100-cada-11eb-904a-04b145dac506.png)

This is probably the preferred method of showing which image is selected as it's more obvious to a user but also reflects the image selection within the metadata viewer [#38].

![Curate Layout -  medium images  – w- image labels  version pop-up v1  – 1](https://user-images.githubusercontent.com/83074763/121720499-17bf6580-cadb-11eb-8497-523c719503ad.png)
![Curate Layout -  medium images  – w- image labels  version side-bar v1  – 1](https://user-images.githubusercontent.com/83074763/121720509-1beb8300-cadb-11eb-93de-1f65d85fe535.png)


https://xd.adobe.com/view/470f7757-f967-42e7-8622-5a9a2d58f500-125c/

**Comment by cooper667** [comment]
> I have gone white but this obviously might not stand out on certain images?

Maybe a 1px black border on it?
